name: Laravel CI/CD

on:
  push:
    branches:
      - main  # Adjust the branch name as needed

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16  # Specify Node.js 16

      - name: Install Composer dependencies
        run: composer install --no-interaction --prefer-dist


