name: Laravel CI/CD

on:
  push:
    branches:
      - main  # Adjust the branch name as needed

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.1  # Adjust the PHP version as needed

      - name: Install Composer dependencies
        run: composer install --no-interaction --prefer-dist

      - name: Run PHPUnit tests
        run: phpunit

      #- name: Deploy to Production
        #if: github.ref == 'refs/heads/main'  # Adjust the branch name as needed
        #run: |
          # Replace this section with your deployment steps.
          # Example:
          # - ssh into your production server
          # - git pull latest changes
          # - run database migrations
          # - restart web server (e.g., Nginx or Apache)

